box = "ubuntu/xenial64"

Vagrant.configure("2") do |config|
  config.vm.box = box

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  conifg.vm.define "master" do |master|
    master.vm.provision "shell", inline: <<-SHELL
      set -e

    SHELL
  end

  conifg.vm.define "node1" do |node1|
    node1.vm.provision "shell", inline: <<-SHELL
      set -e

    SHELL
  end

  conifg.vm.define "node2" do |node2|
    node2.vm.provision "shell", inline: <<-SHELL
      set -e

    SHELL
  end
end
