version: '3.3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx

    
  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:0.4.2
    ports:
      - "9113:9113"
    command:
      - -nginx.scrape-uri
      - http://nginx:80/stub_status

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
