version: '3.3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx

    
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.4.2
    ports:
      - "9113:9113"
        #    environment:
        #      - SCRAPE_URI=http://nginx/stub_status
    command:
      - -nginx.scrape-uri
      - nginx:80/stub_status

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
         
